### ISSUE TITLE
New label for proposals/ideas

### ISSUE THREAD

**Issue by shuruev** [shuruev/Releaser#6]
Sometime it's good to have a place where you could write some ideas just not to forget it.
I created a new label for that.

I called it `proposal`, but probably `idea` suits better.
I also would like to use this tag for other's ideas, like Andrei created today.

What do you think?
Should we rename it to `idea`? :)

**Comment by pbelousov** [comment]
I think this label is a good idea because we have a lot of undefined features and such issues help us to discuss and decide which of them we want to include into project. 

I think it does not matter how to call label because we understand what this label means. If you'd like to rename it to `idea`, I don't mind. :)

**Comment by shuruev** [comment]
Okey, let it be `idea` for now.
